"""
nonlinearity_studies — backwards-compatibility shim.

This module was split into focused submodules.  Everything is re-exported
here (including private, underscore-prefixed helpers) so existing imports
such as `from ...nonlinearity_studies import name` keep working unchanged.
"""

from pedestal_subtract.core import (
    convert_to_electrons,
    _smooth_counts,
    _make_histogram,
    _estimate_peak_width,
    _clip_to_bounds,
    _auto_zero_one_setup,
    calculate_noise_gain,
    double_gauss,
    pedestal_subtract,
    _PEDSUB_ALGO_VERSION,
    _PEDSUB_HEADER_KEYS,
    _pedsub_cache_path,
    _pedsub_header_matches,
    pedestal_subtract_ext_cached,
    _finish_fig,
    _double_gauss_popt_electrons,
    plot_zero_one_peaks,
    get_fits,
    _value_for_extension,
    get_zero_one_peaks_ext,
)
from .fit_data import (
    find_all_peaks,
    fit_nonlinearity,
    _gauss_single,
    _make_comb_model,
    parabola,
)
from .fit_range import (
    estimate_optimal_fit_range_right,
    estimate_optimal_fit_range_right_ext,
    estimate_fit_range_right_by_noise_onset,
    estimate_fit_range_right_by_noise_onset_ext,
    _local_roughness,
    estimate_fit_range_right_changepoint,
    estimate_fit_range_right_changepoint_ext,
)
from .nonlinearity import (
    get_nonlinearity_at,
    get_all_peaks_ext,
    get_nonlinearity_ext,
    get_nonlinearity_at_ext,
)
from .resolution import (
    _resolution_poisson_weights,
    _resolution_reduced_chi2,
    _resolution_poisson_deviance,
    resolution_at_charge,
    classify_resolution,
    resolution_at_charge_ext,
    _RESOLUTION_FIELDS,
    _resolution_record,
    format_resolution_table,
    summarize_resolution,
)
from .plotting import (
    _xlim_window,
    _auto_ylim_in_window,
    plot_all_peaks,
    _resolve_nonlinearity_xbounds,
    _auto_nonlinearity_ylim,
    plot_nonlinearity,
    _RESOLUTION_VERDICT_COLORS,
    _draw_resolution_window,
    plot_resolution,
)
from .summary import (
    _normalize_charges,
    _nonlin_column_name,
    _RESOLUTION_WIDE_FIELDS,
    _resolution_column_name,
    _resolution_wide_fieldnames,
    build_resolution_summary_wide,
    build_extension_summary,
    _summary_fieldnames,
    _RESOLUTION_TERSE_FIELDS,
    format_extension_summary,
    summarize_extensions,
)

__all__ = [
    "find_all_peaks",
    "fit_nonlinearity",
    "_gauss_single",
    "_make_comb_model",
    "parabola",
    "estimate_optimal_fit_range_right",
    "estimate_optimal_fit_range_right_ext",
    "estimate_fit_range_right_by_noise_onset",
    "estimate_fit_range_right_by_noise_onset_ext",
    "_local_roughness",
    "estimate_fit_range_right_changepoint",
    "estimate_fit_range_right_changepoint_ext",
    "get_nonlinearity_at",
    "get_all_peaks_ext",
    "get_nonlinearity_ext",
    "get_nonlinearity_at_ext",
    "_resolution_poisson_weights",
    "_resolution_reduced_chi2",
    "_resolution_poisson_deviance",
    "resolution_at_charge",
    "classify_resolution",
    "resolution_at_charge_ext",
    "_RESOLUTION_FIELDS",
    "_resolution_record",
    "format_resolution_table",
    "summarize_resolution",
    "_xlim_window",
    "_auto_ylim_in_window",
    "plot_all_peaks",
    "_resolve_nonlinearity_xbounds",
    "_auto_nonlinearity_ylim",
    "plot_nonlinearity",
    "_RESOLUTION_VERDICT_COLORS",
    "_draw_resolution_window",
    "plot_resolution",
    "_normalize_charges",
    "_nonlin_column_name",
    "_RESOLUTION_WIDE_FIELDS",
    "_resolution_column_name",
    "_resolution_wide_fieldnames",
    "build_resolution_summary_wide",
    "build_extension_summary",
    "_summary_fieldnames",
    "_RESOLUTION_TERSE_FIELDS",
    "format_extension_summary",
    "summarize_extensions",
    "convert_to_electrons",
    "_smooth_counts",
    "_make_histogram",
    "_estimate_peak_width",
    "_clip_to_bounds",
    "_auto_zero_one_setup",
    "calculate_noise_gain",
    "double_gauss",
    "pedestal_subtract",
    "_PEDSUB_ALGO_VERSION",
    "_PEDSUB_HEADER_KEYS",
    "_pedsub_cache_path",
    "_pedsub_header_matches",
    "pedestal_subtract_ext_cached",
    "_finish_fig",
    "_double_gauss_popt_electrons",
    "plot_zero_one_peaks",
    "get_fits",
    "_value_for_extension",
    "get_zero_one_peaks_ext",
]
